type RegisteredUser = {
    _id: string,
    activeMember: boolean,
    profileImg: string,
    firstName: string,
    lastName: string,
    spiritualName: string,
    email: string | null,
    emailVisible: boolean,
    address: string | null,
    addressVisible: boolean,
    birthday: string | null,
    birthdayVisible: boolean,
    emEmail: string | null,
    emMobile: string | null,
    emName: string | null,
    emContactVisible: boolean,
    gender: string | null,
    genderVisible: boolean,
    level: string | '-',
    mobile: string | null,
    mobileVisible: boolean,
};
